/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softmath;

import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author Usuario
 */
public class HelpDialog extends javax.swing.JDialog {

    private HTMLEditorKit kit;
    private String htmlString;
    private Document doc;

    /**
     * Creates new form AyudaDialog
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        cargarHtml();
        initComponents();

    }

    private void cargarHtml() {
        kit = new HTMLEditorKit();

       

        // create some simple html as a string
        htmlString = "<html>\n"
                + "<body>\n"
                + "<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style='border-top-width: 1px;'>\n"
                + "<tbody>\n"
                + "<tr>\n"
                + "<td valign=\"top\"><strong>Funciones</strong></td>\n"
                + "<td valign=\"top\"><strong>Operadores</strong></td>\n"
                + "</tr>\n"
                + "<tr>\n"
                + "<td valign=\"top\">\n"
                + "<ul>\n"
                + "<li>abs(<i>expresión</i>): valor absoluto</li>\n"
                + "<li>acos(<i>expresión</i>): arco coseno</li>\n"
                + "<li>asin(<i>expresión</i>): arco seno</li>\n"
                + "<li>atan(<i>expresión</i>): arco tangente</li>\n"
                + "<li>cbrt(<i>expresión</i>): raíz cubica</li>\n"
                + "<li>ceil(<i>expresión</i>): número entero más proximo</li>\n"
                + "<li>cos(<i>expresión</i>): coseno</li>\n"
                + "<li>cosh(<i>expresión</i>): coseno hiperbolica</li>\n"
                + "<li>e: el número de Euler elevado a la potencia (e^x)</li>\n"
                + "<li>floor(<i>expresión</i>): número entero inferior más cercano</li>\n"
                + "<li>ln(<i>expresión</i>): logaritmo natural</li>\n"
                + "<li>log(<i>expresión</i>): logaritmo base 10</li>\n"
                + "<li>sin(<i>expresión</i>): seno</li>\n"
                + "<li>sinh(<i>expresión</i>): seno hiperbola</li>\n"
                + "<li>sqrt(<i>expresión</i>): raíz cuadrada</li>\n"
                + "<li>tan(<i>expresión</i>): tangente</li>\n"
                + "<li>tanh(<i>expresión</i>): tangente hiperbolica</li>\n"
                + "</ul>\n"
                + "</td>\n"
                + "<td valign=\"top\">\n"
                + "<ul>\n"
                + "<li>Suma: &#8217;2 + 2&#8242;</li>\n"
                + "<li>Resta: &#8217;2 &#8211; 2&#8242;</li>\n"
                + "<li>Producto: &#8217;2 * 2&#8242;</li>\n"
                + "<li>División: &#8217;2 / 2&#8242;</li>\n"
                + "<li>Potencia: &#8217;2 ^ 2&#8242;</li>\n"
                + "<li>Ley operador: &#8216;+2 &#8211; (-2)&#8217;</li>\n"
                + "<li>Modulo: &#8217;2 % 2&#8242;</li>\n"
                + "</ul>\n"
                + "</td>\n"
                + "</tr>\n"
                + "</tbody>\n"
                + "</table>"
                + "</body>\n"
                + "</html>\n";
        // create a document, set it on the jeditorpane, then add the html
        doc = kit.createDefaultDocument();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editorPanehtml = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfNota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda");
        setModal(true);
        setResizable(false);

        editorPanehtml.setEditable(false);
        editorPanehtml.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.disabledBackground"));
        editorPanehtml.setDocument(doc);
        editorPanehtml.setEditorKit(kit);
        editorPanehtml.setText(htmlString);
        jScrollPane1.setViewportView(editorPanehtml);

        tfNota.setEditable(false);
        tfNota.setBackground(javax.swing.UIManager.getDefaults().getColor("ScrollBar.foreground"));
        tfNota.setColumns(20);
        tfNota.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        tfNota.setForeground(java.awt.Color.red);
        tfNota.setLineWrap(true);
        tfNota.setRows(3);
        tfNota.setText("NOTA: LAS FUNCIONES DEBEN COLOCARSE ENTRE PARENTESIS EJEMPLO tan (x), log (x); también hay que colocar de manera explicita el producto ejemplo: 4*tan (x)");
        jScrollPane2.setViewportView(tfNota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(592, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPanehtml;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tfNota;
    // End of variables declaration//GEN-END:variables
}
