/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package softmath;

import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ViewSoftMath extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public ViewSoftMath() {
        initComponents();
        
        tableResultado.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableResultado.getColumnModel().getColumn(1).setPreferredWidth(260);
        tableResultado.getColumnModel().getColumn(2).setPreferredWidth(130);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMetodo = new javax.swing.ButtonGroup();
        panelDesarrollo = new javax.swing.JPanel();
        scrollPaneDesarrollo = new javax.swing.JScrollPane();
        tableResultado = new javax.swing.JTable();
        lbSumatoria = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        tfSumatoria = new javax.swing.JTextField();
        tfResultado = new javax.swing.JTextField();
        panelIntegral = new javax.swing.JPanel();
        tfB = new javax.swing.JTextField();
        tfA = new javax.swing.JTextField();
        tfFuncion = new javax.swing.JTextField();
        lbDx = new javax.swing.JLabel();
        lbN = new javax.swing.JLabel();
        tfN = new javax.swing.JTextField();
        tfDelta = new javax.swing.JTextField();
        lbDx1 = new javax.swing.JLabel();
        lbDx2 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        btCalcular1 = new javax.swing.JButton();
        btAyuda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbSimpson3_8 = new javax.swing.JRadioButton();
        rbSimpson_abierto = new javax.swing.JRadioButton();
        rbTrapezoidal = new javax.swing.JRadioButton();
        rbSimpson1_3 = new javax.swing.JRadioButton();
        rbBoole = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software de soluciones integrales definidas.");
        setBackground(new java.awt.Color(0, 102, 204));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);

        panelDesarrollo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TABLA DE SOLUCIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 11))); // NOI18N

        scrollPaneDesarrollo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        scrollPaneDesarrollo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Xi", "f(x)", "Resultado"
            }
        ));
        tableResultado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        scrollPaneDesarrollo.setViewportView(tableResultado);

        lbSumatoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lbSumatoria.setText("SUMA");

        lbResultado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lbResultado.setText("RESULTADO");

        tfSumatoria.setEditable(false);
        tfSumatoria.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        tfResultado.setEditable(false);
        tfResultado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        panelIntegral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfB.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tfB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tfA.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        tfA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tfFuncion.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        tfFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFuncionActionPerformed(evt);
            }
        });

        lbDx.setFont(new java.awt.Font("Bodoni MT Condensed", 3, 18)); // NOI18N

        lbN.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lbN.setText("Nro. de interaciones");

        tfN.setText("0");

        tfDelta.setEditable(false);
        tfDelta.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        lbDx1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbDx1.setText("b");

        lbDx2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lbDx2.setText("a");

        btCalcular.setBackground(new java.awt.Color(102, 255, 204));
        btCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCalcular.setMnemonic('c');
        btCalcular.setText("DESARROLLO");
        btCalcular.setToolTipText("Hallar intergal.");
        btCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        btCalcular1.setBackground(new java.awt.Color(51, 255, 204));
        btCalcular1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCalcular1.setMnemonic('c');
        btCalcular1.setText("VACIAR");
        btCalcular1.setToolTipText("Hallar intergal.");
        btCalcular1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btAyuda.setBackground(new java.awt.Color(102, 255, 204));
        btAyuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAyuda.setMnemonic('a');
        btAyuda.setText("AYUDA");
        btAyuda.setToolTipText("Ayuda");
        btAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAyuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAyuda.setFocusable(false);
        btAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAyuda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAyudaActionPerformed(evt);
            }
        });

        jLabel2.setText("DELTA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Integral");

        javax.swing.GroupLayout panelIntegralLayout = new javax.swing.GroupLayout(panelIntegral);
        panelIntegral.setLayout(panelIntegralLayout);
        panelIntegralLayout.setHorizontalGroup(
            panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIntegralLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIntegralLayout.createSequentialGroup()
                        .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIntegralLayout.createSequentialGroup()
                                .addComponent(tfFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelIntegralLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(lbDx2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(lbDx1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(208, 208, 208)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelIntegralLayout.createSequentialGroup()
                        .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIntegralLayout.createSequentialGroup()
                                .addComponent(lbN)
                                .addGap(34, 34, 34)
                                .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelIntegralLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelIntegralLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelIntegralLayout.setVerticalGroup(
            panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIntegralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDelta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDx1)
                    .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDx2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelIntegralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout panelDesarrolloLayout = new javax.swing.GroupLayout(panelDesarrollo);
        panelDesarrollo.setLayout(panelDesarrolloLayout);
        panelDesarrolloLayout.setHorizontalGroup(
            panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesarrolloLayout.createSequentialGroup()
                .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDesarrolloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneDesarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                            .addComponent(panelIntegral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDesarrolloLayout.createSequentialGroup()
                        .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDesarrolloLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbResultado))
                            .addGroup(panelDesarrolloLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDesarrolloLayout.setVerticalGroup(
            panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDesarrolloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDesarrolloLayout.createSequentialGroup()
                        .addComponent(panelIntegral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(scrollPaneDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(lbResultado))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(201, 76, 76));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("METODOS NUMERICOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(398, 398, 398))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroupMetodo.add(rbSimpson3_8);
        rbSimpson3_8.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rbSimpson3_8.setText("T.SIMPSON 3/8-NEWTON");
        rbSimpson3_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimpson3_8ActionPerformed(evt);
            }
        });

        buttonGroupMetodo.add(rbSimpson_abierto);
        rbSimpson_abierto.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rbSimpson_abierto.setText("SIMPSON ABIERTO");
        rbSimpson_abierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimpson_abiertoActionPerformed(evt);
            }
        });

        buttonGroupMetodo.add(rbTrapezoidal);
        rbTrapezoidal.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rbTrapezoidal.setText("TRAPEZOIDAL");
        rbTrapezoidal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTrapezoidalActionPerformed(evt);
            }
        });

        buttonGroupMetodo.add(rbSimpson1_3);
        rbSimpson1_3.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rbSimpson1_3.setSelected(true);
        rbSimpson1_3.setText("T.SIMPSON 1/3-NEWTON");
        rbSimpson1_3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        rbSimpson1_3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        rbSimpson1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSimpson1_3ActionPerformed(evt);
            }
        });

        buttonGroupMetodo.add(rbBoole);
        rbBoole.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        rbBoole.setText("JORGE BOOLE");
        rbBoole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBooleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rbSimpson1_3)
                        .addGap(18, 18, 18)
                        .addComponent(rbBoole)
                        .addGap(18, 18, 18)
                        .addComponent(rbSimpson3_8)
                        .addGap(60, 60, 60)
                        .addComponent(rbSimpson_abierto)
                        .addGap(54, 54, 54)
                        .addComponent(rbTrapezoidal))
                    .addComponent(panelDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSimpson1_3)
                    .addComponent(rbSimpson3_8)
                    .addComponent(rbSimpson_abierto)
                    .addComponent(rbTrapezoidal)
                    .addComponent(rbBoole))
                .addGap(11, 11, 11)
                .addComponent(panelDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbSimpson1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimpson1_3ActionPerformed
        seleccionarRadioMetodo(1);
    }//GEN-LAST:event_rbSimpson1_3ActionPerformed

    private void rbSimpson3_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimpson3_8ActionPerformed
        seleccionarRadioMetodo(2);
    }//GEN-LAST:event_rbSimpson3_8ActionPerformed

    private void rbBooleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBooleActionPerformed
        seleccionarRadioMetodo(3);
    }//GEN-LAST:event_rbBooleActionPerformed

    private void rbTrapezoidalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTrapezoidalActionPerformed
       seleccionarRadioMetodo(4);
    }//GEN-LAST:event_rbTrapezoidalActionPerformed

    private void rbSimpson_abiertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSimpson_abiertoActionPerformed
        seleccionarRadioMetodo(5);
    }//GEN-LAST:event_rbSimpson_abiertoActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
       calcularIntegral();
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        tfA.setText("");
        tfB.setText("");
        tfDelta.setText("");
        tfN.setText("0");
        tfFuncion.setText("");
        tfResultado.setText("");
        tfSumatoria.setText("");
        seleccionarRadioMetodo(1);
        borrarTabla();
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAyudaActionPerformed
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final HelpDialog dialog = new HelpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        dialog.dispose();
                    }
                });
                dialog.setVisible(true);
            }
        });
    }//GEN-LAST:event_btAyudaActionPerformed

    private void tfFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFuncionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFuncionActionPerformed

    public void seleccionarRadioMetodo(int index){
        if(index==4 || index == 5){
            lbN.setVisible(true);
            tfN.setVisible(true);
        }else{
            lbN.setVisible(false);
            tfN.setVisible(false);
            tfN.setText("0");
        }
    }
    
    @SuppressWarnings("CallToThreadDumpStack")
    private void calcularIntegral(){
        if(!validarValoresAyB()){
            return;
        }
        if(!validarValorN()){
            return;
        }
        double a = Double.parseDouble(tfA.getText().trim());
        double b = Double.parseDouble(tfB.getText().trim());
        int n = Integer.parseInt(tfN.getText().trim());
        if(a>=b){
            JOptionPane.showMessageDialog(this, "El valor de \"a\" no puede "
                    + "ser mayor ni igual que \"b\"", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(n<=0 && (rbTrapezoidal.isSelected() || rbSimpson_abierto.isSelected())){
            JOptionPane.showMessageDialog(this, "El valor de \"N\" no puede "
                    + "ser menor ni igual que \"Cero (0)\"", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(tfFuncion.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite el valor de la función", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Clasificatoria metodo = getMetodo();
        ReturnDelta delta = new ReturnDelta(a, b, n, metodo);
        tfDelta.setText(RepositorioNumerico.formatDecimal(delta.getValor_delta(),
                "#,##0.00"));
        
        if(rbSimpson1_3.isSelected()){
            n = 3;
        }else if(rbSimpson3_8.isSelected()){
            n = 4;
        }else if(rbBoole.isSelected()){
            n = 5;
        }else if(rbTrapezoidal.isSelected()||rbSimpson_abierto.isSelected()){
            n = n+1;
        }
        
        try {
            ResolucionIntegral resolucionIntegral = new ResolucionIntegral(a, b, n, delta, metodo);
            List<Map> lista_sumatoria = resolucionIntegral.desarrolloSumatoria(tfFuncion.getText());
            borrarTabla();
            DefaultTableModel tableModel = (DefaultTableModel) tableResultado.getModel();
            double sumatoria = 0;
            for (int i = 0; i < lista_sumatoria.size(); i++) {
                Map map = lista_sumatoria.get(i);
                int producto = (Integer)map.get("producto");
                double xi =(Double) map.get("xi");
                double fxi = (Double)map.get("fxi");
                double resultado = (fxi*producto);
                sumatoria+=(resultado);
                tableModel.addRow(new Object[]{
                    RepositorioNumerico.formatDecimal(xi, "#,##0.00"),
                    (producto>1?producto+" * [ ":" [ ")+map.get("expresion")+" ]",
                    resultado
                });
            }
            double integral = ReturnIntegrall.resultadoIntegral(delta, sumatoria, metodo);
            
            tfSumatoria.setText(sumatoria+"");
            tfResultado.setText(integral+"");
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage(), 
                    "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }
    
    public void borrarTabla(){
        int rowCount = tableResultado.getRowCount();
        while(rowCount>0){
            DefaultTableModel tableModel = (DefaultTableModel) tableResultado.getModel();
            tableModel.removeRow(rowCount-1);
            rowCount--;
        }
    }
    
    public boolean validarValoresAyB(){
        if(tfA.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe digitar el valor de \"a\"", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if(tfB.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe digitar el valor de \"b\"", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            Double.parseDouble(tfA.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor de \"a\" es invalido", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            Double.parseDouble(tfB.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor de \"b\" es invalido", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    public boolean validarValorN(){
        if(tfN.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe digitar el valor de \"N\"", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            int n = Integer.parseInt(tfN.getText().trim());
            if((n % 2)!= 0 && rbSimpson_abierto.isSelected()){
                 JOptionPane.showMessageDialog(this, "Para simsomp abierto el valor de \"N\" debe ser par", 
                    "Error", JOptionPane.WARNING_MESSAGE);
                    return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El valor de \"N\" es invalido debe ser entero", 
                    "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        
        return true;
    }
    
    public Clasificatoria getMetodo(){
        if(rbSimpson1_3.isSelected()){
            return Clasificatoria.SIMPSON_1_3;
        }else if(rbSimpson3_8.isSelected()){
            return Clasificatoria.SIMPSON_3_8;
        }else if(rbBoole.isSelected()){
            return Clasificatoria.BOOLE;
        }else if(rbTrapezoidal.isSelected()){
            return Clasificatoria.TRAPEZOIDAL;
        }else if(rbSimpson_abierto.isSelected()){
            return Clasificatoria.SIMPSON_ABIERTO;
        }
        return Clasificatoria.SIMPSON_1_3;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAyuda;
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btCalcular1;
    private javax.swing.ButtonGroup buttonGroupMetodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDx;
    private javax.swing.JLabel lbDx1;
    private javax.swing.JLabel lbDx2;
    private javax.swing.JLabel lbN;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbSumatoria;
    private javax.swing.JPanel panelDesarrollo;
    private javax.swing.JPanel panelIntegral;
    private javax.swing.JRadioButton rbBoole;
    private javax.swing.JRadioButton rbSimpson1_3;
    private javax.swing.JRadioButton rbSimpson3_8;
    private javax.swing.JRadioButton rbSimpson_abierto;
    private javax.swing.JRadioButton rbTrapezoidal;
    private javax.swing.JScrollPane scrollPaneDesarrollo;
    private javax.swing.JTable tableResultado;
    private javax.swing.JTextField tfA;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfDelta;
    private javax.swing.JTextField tfFuncion;
    private javax.swing.JTextField tfN;
    private javax.swing.JTextField tfResultado;
    private javax.swing.JTextField tfSumatoria;
    // End of variables declaration//GEN-END:variables
}
